### ISSUE TITLE
# QMS Import Testing Checklist

### ISSUE THREAD

**Issue by akhismat** [akhismat/test-huly#317]
# QMS Import Testing Checklist

### Required Fields
- [ ] class
  - [ ] отсутствует поле
  - [ ] пустая строка
  - [ ] неверный тип (число вместо строки)
  - [ ] неверное значение (не documents:class:OrgSpace)

- [ ] title
  - [ ] отсутствует поле
  - [ ] пустая строка
  - [ ] неверный тип (массив вместо строки)

### Optional Fields
- [ ] private
  - [ ] неверный тип (строка вместо boolean)
  - [ ] отсутствует поле (должен использоваться default: false)

- [ ] owners
  - [ ] неверный тип (строка вместо массива)
  - [ ] невалидный email
  - [ ] пустой массив

- [ ] members
  - [ ] неверный тип (строка вместо массива)
  - [ ] невалидный email
  - [ ] пустой массив

- [ ] description
  - [ ] неверный тип (массив вместо строки)

- [ ] qualified
  - [ ] неверный тип (массив вместо строки)
  - [ ] невалидный email

- [ ] manager
  - [ ] неверный тип (массив вместо строки)
  - [ ] невалидный email

- [ ] qara
  - [ ] неверный тип (массив вместо строки)
  - [ ] невалидный email

### Required Fields
- [ ] class
  - [ ] отсутствует поле
  - [ ] пустая строка
  - [ ] неверный тип (число вместо строки)
  - [ ] неверное значение (не documents:mixin:DocumentTemplate)

- [ ] title
  - [ ] отсутствует поле
  - [ ] пустая строка
  - [ ] неверный тип (число вместо строки)

- [ ] docPrefix
  - [ ] отсутствует поле
  - [ ] пустая строка
  - [ ] неверный тип (массив вместо строки)

- [ ] category
  - [ ] отсутствует поле
  - [ ] пустая строка
  - [ ] неверный тип (число вместо строки)
  - [ ] неверное значение (не из списка documents:category:*)

- [ ] author
  - [ ] отсутствует поле
  - [ ] пустая строка
  - [ ] неверный тип (массив вместо строки)
  - [ ] несуществующий пользователь

- [ ] owner
  - [ ] отсутствует поле
  - [ ] пустая строка
  - [ ] неверный тип (массив вместо строки)
  - [ ] несуществующий пользователь

### Optional Fields
- [ ] abstract
  - [ ] неверный тип (массив вместо строки)

- [ ] reviewers
  - [ ] неверный тип (строка вместо массива)
  - [ ] несуществующий пользователь
  - [ ] пустой массив

- [ ] approvers
  - [ ] неверный тип (строка вместо массива)
  - [ ] несуществующий пользователь
  - [ ] пустой массив

- [ ] coAuthors
  - [ ] неверный тип (строка вместо массива)
  - [ ] несуществующий пользователь
  - [ ] пустой массив

### Required Fields
- [ ] class
  - [ ] отсутствует поле
  - [ ] пустая строка
  - [ ] неверный тип (число вместо строки)
  - [ ] неверное значение (не documents:class:ControlledDocument)

- [ ] title
  - [ ] отсутствует поле
  - [ ] пустая строка
  - [ ] неверный тип (число вместо строки)

- [ ] template
  - [ ] отсутствует поле
  - [ ] пустая строка
  - [ ] неверный тип (массив вместо строки)
  - [ ] несуществующий шаблон
  - [ ] шаблон из другого пространства

- [ ] author
  - [ ] отсутствует поле
  - [ ] пустая строка
  - [ ] неверный тип (массив вместо строки)
  - [ ] несуществующий пользователь

- [ ] owner
  - [ ] отсутствует поле
  - [ ] пустая строка
  - [ ] неверный тип (массив вместо строки)
  - [ ] несуществующий пользователь

### Optional Fields
- [ ] abstract
  - [ ] неверный тип (массив вместо строки)

- [ ] reviewers
  - [ ] неверный тип (строка вместо массива)
  - [ ] несуществующий пользователь
  - [ ] пустой массив

- [ ] approvers
  - [ ] неверный тип (строка вместо массива)
  - [ ] несуществующий пользователь
  - [ ] пустой массив

- [ ] coAuthors
  - [ ] неверный тип (строка вместо массива)
  - [ ] несуществующий пользователь
  - [ ] пустой массив

- [ ] changeControl
  - [ ] неверный тип (строка вместо объекта)
  - [ ] description неверного типа
  - [ ] reason неверного типа
  - [ ] impact неверного типа
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.
